"""Add settings table

Revision ID: db9c13132abd
Revises: x3t01u2v4w56
Create Date: 2025-12-14 13:33:15.616024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db9c13132abd'
down_revision: Union[str, Sequence[str], None] = 'x3t01u2v4w56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_id'), 'settings', ['id'], unique=False)
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=True)
    op.drop_index(op.f('ix_ai_api_keys_provider_id'), table_name='ai_api_keys')
    op.drop_index(op.f('ix_ai_conversations_organization_id'), table_name='ai_conversations')
    op.drop_index(op.f('ix_ai_conversations_person_id'), table_name='ai_conversations')
    op.alter_column('ai_data_access_settings', 'auto_apply_suggestions',
               existing_type=sa.BOOLEAN(),
               comment='Auto-apply AI suggestions without approval (default: require approval)',
               existing_comment='Auto-apply AI suggestions without approval',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_ai_messages_conversation_id'), table_name='ai_messages')
    op.drop_index(op.f('ix_ai_suggestions_conversation_id'), table_name='ai_suggestions')
    op.drop_index(op.f('ix_ai_suggestions_entity'), table_name='ai_suggestions')
    op.drop_index(op.f('ix_ai_suggestions_status'), table_name='ai_suggestions')
    op.alter_column('email_messages', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('email_messages', 'is_starred',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('email_messages', 'is_draft',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('email_messages', 'is_sent',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               comment="True if from user's sent folder",
               existing_comment='True if from user sent folder',
               existing_server_default=sa.text('false'))
    op.alter_column('email_messages', 'has_attachments',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('email_messages', 'attachment_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('email_messages', 'synced_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('email_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('email_messages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_email_messages_date'), table_name='email_messages')
    op.create_index('idx_email_messages_date', 'email_messages', ['internal_date'], unique=False, postgresql_ops={'internal_date': 'DESC'})
    op.alter_column('email_person_links', 'linked_by',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_comment='How link was created: auto or manual',
               existing_server_default=sa.text("'auto'::character varying"))
    op.alter_column('email_person_links', 'linked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('email_sync_state', 'sync_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'never_synced'::character varying"))
    op.alter_column('email_sync_state', 'messages_synced',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Total messages synced from this account',
               existing_server_default=sa.text('0'))
    op.alter_column('email_sync_state', 'last_sync_message_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Messages synced in last sync operation',
               existing_server_default=sa.text('0'))
    op.alter_column('email_sync_state', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('email_sync_state', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('import_history', 'source',
               existing_type=postgresql.ENUM('linkedin', 'google_contacts', 'csv', 'other', name='importsource'),
               comment='Source of the import (linkedin, google_contacts, csv, etc.)',
               existing_nullable=False)
    op.alter_column('import_history', 'status',
               existing_type=postgresql.ENUM('success', 'partial', 'failed', name='importstatus'),
               comment='Status of the import operation',
               existing_nullable=False)
    op.alter_column('import_history', 'original_filename',
               existing_type=sa.VARCHAR(length=255),
               comment='Original name of the uploaded file',
               existing_nullable=False)
    op.alter_column('import_history', 'stored_filename',
               existing_type=sa.VARCHAR(length=255),
               comment='Name of the stored file on disk (UUID-based)',
               existing_nullable=True)
    op.alter_column('import_history', 'file_size_bytes',
               existing_type=sa.INTEGER(),
               comment='Size of the uploaded file in bytes',
               existing_nullable=True)
    op.alter_column('import_history', 'records_parsed',
               existing_type=sa.INTEGER(),
               comment='Number of records parsed from the file',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('import_history', 'records_created',
               existing_type=sa.INTEGER(),
               comment='Number of new records created',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('import_history', 'records_updated',
               existing_type=sa.INTEGER(),
               comment='Number of existing records updated',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('import_history', 'records_skipped',
               existing_type=sa.INTEGER(),
               comment='Number of records skipped (duplicates, errors)',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('import_history', 'organizations_created',
               existing_type=sa.INTEGER(),
               comment='Number of organizations created during import',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('import_history', 'error_message',
               existing_type=sa.TEXT(),
               comment='Error message if import failed',
               existing_nullable=True)
    op.alter_column('import_history', 'imported_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When the import was performed',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('import_logs', 'import_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('import_logs', 'records_processed',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('import_logs', 'records_imported',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('import_logs', 'records_skipped',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('interactions', 'gmail_thread_id',
               existing_type=sa.VARCHAR(length=255),
               comment='Gmail thread ID for viewing in Gmail',
               existing_nullable=True)
    op.alter_column('interactions', 'gmail_message_id',
               existing_type=sa.VARCHAR(length=255),
               comment='Gmail message ID for direct message link',
               existing_nullable=True)
    op.alter_column('interactions', 'source',
               existing_type=postgresql.ENUM('manual', 'email', 'calendar', name='interaction_source'),
               comment='Source of interaction: manual entry, email import, or calendar sync',
               existing_nullable=False,
               existing_server_default=sa.text("'manual'::interaction_source"))
    op.alter_column('interactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('interactions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_interactions_date'), table_name='interactions')
    op.drop_index(op.f('idx_interactions_gmail_thread'), table_name='interactions', postgresql_where='(gmail_thread_id IS NOT NULL)')
    op.drop_index(op.f('idx_interactions_medium'), table_name='interactions')
    op.drop_index(op.f('idx_interactions_person'), table_name='interactions')
    op.drop_constraint(op.f('uq_organization_categories_code'), 'organization_categories', type_='unique')
    op.drop_index(op.f('ix_organization_categories_code'), table_name='organization_categories')
    op.create_index(op.f('ix_organization_categories_code'), 'organization_categories', ['code'], unique=True)
    op.drop_index(op.f('ix_organization_offices_organization_id'), table_name='organization_offices')
    op.drop_index(op.f('ix_organization_relationship_status_organization_id'), table_name='organization_relationship_status')
    op.alter_column('organization_relationships', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('organization_tags', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_org_tags_org'), table_name='organization_tags')
    op.drop_index(op.f('idx_org_tags_tag'), table_name='organization_tags')
    op.drop_constraint(op.f('uq_organization_types_code'), 'organization_types', type_='unique')
    op.drop_index(op.f('ix_organization_types_code'), table_name='organization_types')
    op.create_index(op.f('ix_organization_types_code'), 'organization_types', ['code'], unique=True)
    op.alter_column('organizations', 'priority_rank',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('organizations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('organizations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_organizations_custom_fields'), table_name='organizations', postgresql_using='gin')
    op.drop_index(op.f('idx_organizations_name'), table_name='organizations')
    op.drop_index(op.f('idx_organizations_org_type'), table_name='organizations')
    op.drop_table_comment(
        'organizations',
        existing_comment='Merged Firms and Companies from Airtable',
        schema=None
    )
    op.alter_column('person_organizations', 'is_current',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('person_organizations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_person_orgs_org'), table_name='person_organizations')
    op.drop_index(op.f('idx_person_orgs_person'), table_name='person_organizations')
    op.drop_index(op.f('idx_person_orgs_relationship'), table_name='person_organizations')
    op.drop_table_comment(
        'person_organizations',
        existing_comment='Person-to-Org links (Invest Firm, Peers)',
        schema=None
    )
    op.alter_column('person_phones', 'is_primary',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('person_phones', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('person_tags', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_person_tags_person'), table_name='person_tags')
    op.drop_index(op.f('idx_person_tags_tag'), table_name='person_tags')
    op.alter_column('persons', 'full_name',
               existing_type=sa.VARCHAR(length=300),
               comment=None,
               existing_comment='Original unsplit name from Airtable',
               existing_nullable=False)
    op.alter_column('persons', 'contacted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('persons', 'birthday',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Person birthday (day and month, year optional)',
               existing_nullable=True)
    op.alter_column('persons', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('persons', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_persons_custom_fields'), table_name='persons', postgresql_using='gin')
    op.drop_index(op.f('idx_persons_email'), table_name='persons')
    op.drop_index(op.f('idx_persons_fts'), table_name='persons', postgresql_using='gin')
    op.drop_index(op.f('idx_persons_full_name'), table_name='persons')
    op.drop_index(op.f('idx_persons_last_name'), table_name='persons')
    op.drop_table_comment(
        'persons',
        existing_comment='Contacts from Airtable Individuals table',
        schema=None
    )
    op.drop_index(op.f('ix_record_snapshots_entity'), table_name='record_snapshots')
    op.alter_column('saved_views', 'sort_order',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'asc'::character varying"))
    op.alter_column('saved_views', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('saved_views', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('saved_views', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tags', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_tags_name'), table_name='tags')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_tags_name'), 'tags', ['name'], unique=False)
    op.alter_column('tags', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('saved_views', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('saved_views', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('saved_views', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('saved_views', 'sort_order',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'asc'::character varying"))
    op.create_index(op.f('ix_record_snapshots_entity'), 'record_snapshots', ['entity_type', 'entity_id'], unique=False)
    op.create_table_comment(
        'persons',
        'Contacts from Airtable Individuals table',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_persons_last_name'), 'persons', ['last_name'], unique=False)
    op.create_index(op.f('idx_persons_full_name'), 'persons', ['full_name'], unique=False)
    op.create_index(op.f('idx_persons_fts'), 'persons', [sa.literal_column("to_tsvector('english'::regconfig, (((((COALESCE(full_name, ''::character varying)::text || ' '::text) || COALESCE(title, ''::text)) || ' '::text) || COALESCE(notes, ''::text)) || ' '::text) || COALESCE(email, ''::text))")], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_persons_email'), 'persons', ['email'], unique=False)
    op.create_index(op.f('idx_persons_custom_fields'), 'persons', ['custom_fields'], unique=False, postgresql_using='gin')
    op.alter_column('persons', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('persons', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('persons', 'birthday',
               existing_type=sa.DATE(),
               comment='Person birthday (day and month, year optional)',
               existing_nullable=True)
    op.alter_column('persons', 'contacted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('persons', 'full_name',
               existing_type=sa.VARCHAR(length=300),
               comment='Original unsplit name from Airtable',
               existing_nullable=False)
    op.create_index(op.f('idx_person_tags_tag'), 'person_tags', ['tag_id'], unique=False)
    op.create_index(op.f('idx_person_tags_person'), 'person_tags', ['person_id'], unique=False)
    op.alter_column('person_tags', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('person_phones', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('person_phones', 'is_primary',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_table_comment(
        'person_organizations',
        'Person-to-Org links (Invest Firm, Peers)',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_person_orgs_relationship'), 'person_organizations', ['relationship'], unique=False)
    op.create_index(op.f('idx_person_orgs_person'), 'person_organizations', ['person_id'], unique=False)
    op.create_index(op.f('idx_person_orgs_org'), 'person_organizations', ['organization_id'], unique=False)
    op.alter_column('person_organizations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('person_organizations', 'is_current',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.create_table_comment(
        'organizations',
        'Merged Firms and Companies from Airtable',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_organizations_org_type'), 'organizations', ['org_type'], unique=False)
    op.create_index(op.f('idx_organizations_name'), 'organizations', ['name'], unique=False)
    op.create_index(op.f('idx_organizations_custom_fields'), 'organizations', ['custom_fields'], unique=False, postgresql_using='gin')
    op.alter_column('organizations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('organizations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('organizations', 'priority_rank',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_organization_types_code'), table_name='organization_types')
    op.create_index(op.f('ix_organization_types_code'), 'organization_types', ['code'], unique=False)
    op.create_unique_constraint(op.f('uq_organization_types_code'), 'organization_types', ['code'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_org_tags_tag'), 'organization_tags', ['tag_id'], unique=False)
    op.create_index(op.f('idx_org_tags_org'), 'organization_tags', ['organization_id'], unique=False)
    op.alter_column('organization_tags', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('organization_relationships', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_organization_relationship_status_organization_id'), 'organization_relationship_status', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_offices_organization_id'), 'organization_offices', ['organization_id'], unique=False)
    op.drop_index(op.f('ix_organization_categories_code'), table_name='organization_categories')
    op.create_index(op.f('ix_organization_categories_code'), 'organization_categories', ['code'], unique=False)
    op.create_unique_constraint(op.f('uq_organization_categories_code'), 'organization_categories', ['code'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_interactions_person'), 'interactions', ['person_id'], unique=False)
    op.create_index(op.f('idx_interactions_medium'), 'interactions', ['medium'], unique=False)
    op.create_index(op.f('idx_interactions_gmail_thread'), 'interactions', ['gmail_thread_id'], unique=False, postgresql_where='(gmail_thread_id IS NOT NULL)')
    op.create_index(op.f('idx_interactions_date'), 'interactions', ['interaction_date'], unique=False)
    op.alter_column('interactions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('interactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('interactions', 'source',
               existing_type=postgresql.ENUM('manual', 'email', 'calendar', name='interaction_source'),
               comment=None,
               existing_comment='Source of interaction: manual entry, email import, or calendar sync',
               existing_nullable=False,
               existing_server_default=sa.text("'manual'::interaction_source"))
    op.alter_column('interactions', 'gmail_message_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Gmail message ID for direct message link',
               existing_nullable=True)
    op.alter_column('interactions', 'gmail_thread_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Gmail thread ID for viewing in Gmail',
               existing_nullable=True)
    op.alter_column('import_logs', 'records_skipped',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('import_logs', 'records_imported',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('import_logs', 'records_processed',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('import_logs', 'import_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('import_history', 'imported_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When the import was performed',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('import_history', 'error_message',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Error message if import failed',
               existing_nullable=True)
    op.alter_column('import_history', 'organizations_created',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Number of organizations created during import',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('import_history', 'records_skipped',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Number of records skipped (duplicates, errors)',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('import_history', 'records_updated',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Number of existing records updated',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('import_history', 'records_created',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Number of new records created',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('import_history', 'records_parsed',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Number of records parsed from the file',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('import_history', 'file_size_bytes',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Size of the uploaded file in bytes',
               existing_nullable=True)
    op.alter_column('import_history', 'stored_filename',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Name of the stored file on disk (UUID-based)',
               existing_nullable=True)
    op.alter_column('import_history', 'original_filename',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Original name of the uploaded file',
               existing_nullable=False)
    op.alter_column('import_history', 'status',
               existing_type=postgresql.ENUM('success', 'partial', 'failed', name='importstatus'),
               comment=None,
               existing_comment='Status of the import operation',
               existing_nullable=False)
    op.alter_column('import_history', 'source',
               existing_type=postgresql.ENUM('linkedin', 'google_contacts', 'csv', 'other', name='importsource'),
               comment=None,
               existing_comment='Source of the import (linkedin, google_contacts, csv, etc.)',
               existing_nullable=False)
    op.alter_column('email_sync_state', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('email_sync_state', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('email_sync_state', 'last_sync_message_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Messages synced in last sync operation',
               existing_server_default=sa.text('0'))
    op.alter_column('email_sync_state', 'messages_synced',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Total messages synced from this account',
               existing_server_default=sa.text('0'))
    op.alter_column('email_sync_state', 'sync_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'never_synced'::character varying"))
    op.alter_column('email_person_links', 'linked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('email_person_links', 'linked_by',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_comment='How link was created: auto or manual',
               existing_server_default=sa.text("'auto'::character varying"))
    op.drop_index('idx_email_messages_date', table_name='email_messages', postgresql_ops={'internal_date': 'DESC'})
    op.create_index(op.f('idx_email_messages_date'), 'email_messages', [sa.literal_column('internal_date DESC')], unique=False)
    op.alter_column('email_messages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('email_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('email_messages', 'synced_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('email_messages', 'attachment_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('email_messages', 'has_attachments',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('email_messages', 'is_sent',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment='True if from user sent folder',
               existing_comment="True if from user's sent folder",
               existing_server_default=sa.text('false'))
    op.alter_column('email_messages', 'is_draft',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('email_messages', 'is_starred',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('email_messages', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_ai_suggestions_status'), 'ai_suggestions', ['status'], unique=False)
    op.create_index(op.f('ix_ai_suggestions_entity'), 'ai_suggestions', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_ai_suggestions_conversation_id'), 'ai_suggestions', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_ai_messages_conversation_id'), 'ai_messages', ['conversation_id'], unique=False)
    op.alter_column('ai_data_access_settings', 'auto_apply_suggestions',
               existing_type=sa.BOOLEAN(),
               comment='Auto-apply AI suggestions without approval',
               existing_comment='Auto-apply AI suggestions without approval (default: require approval)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_ai_conversations_person_id'), 'ai_conversations', ['person_id'], unique=False)
    op.create_index(op.f('ix_ai_conversations_organization_id'), 'ai_conversations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_ai_api_keys_provider_id'), 'ai_api_keys', ['provider_id'], unique=False)
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.drop_index(op.f('ix_settings_id'), table_name='settings')
    op.drop_table('settings')
    # ### end Alembic commands ###
